

CREATE TABLE `events` (
  `eventPK` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `clid` int(10) unsigned NOT NULL,
  `dbpk` varchar(150) DEFAULT NULL,
  `eventID` varchar(150) DEFAULT NULL,
  `parentEventID` varchar(150) DEFAULT NULL,
  `parentEventPK` int(10) unsigned NULL,
  `eventType` varchar(150) DEFAULT NULL,
  `fieldNumber` varchar(45) DEFAULT NULL,
  `eventDate` date DEFAULT NULL,
  `eventDate2` date DEFAULT NULL,
  `eventTime` varchar(45) DEFAULT NULL,
  `eventTime2` varchar(45) DEFAULT NULL,
  `year` int(10) DEFAULT NULL,
  `month` int(10) DEFAULT NULL,
  `day` int(10) DEFAULT NULL,
  `startDayOfYear` int(10) DEFAULT NULL,
  `endDayOfYear` int(10) DEFAULT NULL,
  `verbatimEventDate` varchar(255) DEFAULT NULL,
  `habitat` text DEFAULT NULL COMMENT 'Habitat, substrait, etc',
  `substrate` varchar(500) DEFAULT NULL,
  `samplingProtocol` varchar(250) DEFAULT NULL,
  `sampleSizeValue` double DEFAULT NULL,
  `sampleSizeUnit` varchar(45) DEFAULT NULL,
  `samplingEffort` varchar(200) DEFAULT NULL,
  `fieldNotes` text DEFAULT NULL,
  `eventRemarks` varchar(100) DEFAULT NULL,
  `locationID` varchar(150) DEFAULT NULL,
  `higherGeography` varchar(250) DEFAULT NULL,
  `continent` varchar(45) DEFAULT NULL,
  `waterBody` varchar(75) DEFAULT NULL,
  `islandGroup` varchar(75) DEFAULT NULL,
  `island` varchar(75) DEFAULT NULL,
  `countryCode` varchar(5) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `adminUnit1` varchar(100) DEFAULT NULL,
  `adminUnit2` varchar(100) DEFAULT NULL,
  `adminUnit3` varchar(100) DEFAULT NULL,
  `locality` text DEFAULT NULL,
  `verbatimLocality` text DEFAULT NULL,
  `localitySecurity` int(10) DEFAULT 0 COMMENT '0 = no security; 1 = hidden locality',
  `localitySecurityReason` varchar(100) DEFAULT NULL,
  `decimalLatitude` double DEFAULT NULL,
  `decimalLongitude` double DEFAULT NULL,
  `geodeticDatum` varchar(255) DEFAULT NULL,
  `coordinateUncertaintyInMeters` int(10) unsigned DEFAULT NULL,
  `footprintWKT` text DEFAULT NULL,
  `geoJson` text DEFAULT NULL,
  `verbatimCoordinates` varchar(255) DEFAULT NULL,
  `georeferencedBy` varchar(255) DEFAULT NULL,
  `georeferencedDate` datetime DEFAULT NULL,
  `georeferenceRemarks` varchar(500) DEFAULT NULL,
  `minimumElevationInMeters` int(6) DEFAULT NULL,
  `maximumElevationInMeters` int(6) DEFAULT NULL,
  `verbatimElevation` varchar(255) DEFAULT NULL,
  `verticalDatum` varchar(45) DEFAULT NULL,
  `minimumDepthInMeters` int(11) DEFAULT NULL,
  `maximumDepthInMeters` int(11) DEFAULT NULL,
  `verbatimDepth` varchar(50) DEFAULT NULL,
  `distanceAboveSurfaceInMeters` varchar(45) DEFAULT NULL,
  `locationRemarks` text DEFAULT NULL,
  `recordID` varchar(45) DEFAULT NULL,
  `createdUid` int(10) unsigned DEFAULT NULL,
  `modifiedTimestamp` timestamp NULL ON UPDATE current_timestamp(),
  `initialTimestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`eventPK`) USING BTREE,
  UNIQUE KEY `UNIQUE_occurrenceID` (`occurrenceID`),
  KEY `IX_locationID` (`locationID`),
  KEY `IX_country` (`country`),
  KEY `IX_adminUnit1` (`adminUnit1`),
  KEY `IX_adminUnit2` (`adminUnit2`),
  KEY `IX_adminUnit3` (`adminUnit3`),
  KEY `IX_decimalLatitute` (`decimalLatitude`),
  KEY `IX_decimalLongitute` (`decimalLongitude`),
  KEY `IX_localitySecurity` (`localitySecurity`),
  KEY `IX_eventDate` (`eventDate`),
  KEY `IX_eventDate2` (`eventDate2`),
  KEY `IX_elevMax` (`maximumElevationInMeters`),
  KEY `IX_elevMin` (`minimumElevationInMeters`),
  KEY `IX_recordID` (`recordID`),
  CONSTRAINT `FK_clid` FOREIGN KEY (`clid`) REFERENCES `fmchecklists` (`clid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_parentEventPK` FOREIGN KEY (`parentEventPK`) REFERENCES `events` (`eventPK`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_createdUid` FOREIGN KEY (`createdUid`) REFERENCES `users` (`uid`)
) ENGINE=InnoDB;

ALTER TABLE `fmchecklists` 
  DROP FOREIGN KEY `FK_checklists_uid`;

ALTER TABLE `fmchecklists` 
  DROP COLUMN `politicalDivision`,
  CHANGE COLUMN `access` `access` VARCHAR(45) NULL DEFAULT 'private' AFTER `type`,
  CHANGE COLUMN `cidKeyLimits` `cidKeyLimits` VARCHAR(250) NULL DEFAULT NULL AFTER `access`,
  CHANGE COLUMN `defaultSettings` `defaultSettings` VARCHAR(250) NULL DEFAULT NULL AFTER `cidKeyLimits`,
  CHANGE COLUMN `iconUrl` `iconUrl` VARCHAR(150) NULL DEFAULT NULL AFTER `defaultSettings`,
  CHANGE COLUMN `headerUrl` `headerUrl` VARCHAR(150) NULL DEFAULT NULL AFTER `iconUrl`,
  CHANGE COLUMN `percentEffort` `percentEffort` DOUBLE NULL DEFAULT NULL AFTER `dynamicSql`,
  CHANGE COLUMN `uid` `createdUid` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `modifiedTimestamp`,
  CHANGE COLUMN `locality` `locality` VARCHAR(1000) NULL DEFAULT NULL ,
  CHANGE COLUMN `guid` `sourceGUID` VARCHAR(45) NULL DEFAULT NULL ,
  CHANGE COLUMN `dateLastModified` `modifiedTimestamp` TIMESTAMP NULL DEFAULT NULL ;

ALTER TABLE `fmchecklists` 
  ADD CONSTRAINT `FK_checklists_uid`  FOREIGN KEY (`createdUid`)  REFERENCES `users` (`uid`);
  
ALTER TABLE `fmchecklists` 
  ADD COLUMN `samplingProtocol` VARCHAR(255) NULL AFTER `dynamicSql`,
  ADD COLUMN `locationID` VARCHAR(150) NULL AFTER `notes`,
  ADD COLUMN `higherGeography` VARCHAR(250) NULL AFTER `locationID`,
  ADD COLUMN `continent` VARCHAR(45) NULL AFTER `higherGeography`,
  ADD COLUMN `waterBody` VARCHAR(75) NULL AFTER `continent`,
  ADD COLUMN `islandGroup` VARCHAR(75) NULL AFTER `waterBody`,
  ADD COLUMN `island` VARCHAR(75) NULL AFTER `islandGroup`,
  ADD COLUMN `countryCode` VARCHAR(5) NULL AFTER `island`,
  ADD COLUMN `country` VARCHAR(64) NULL AFTER `countryCode`,
  ADD COLUMN `adminUnit1` VARCHAR(100) NULL AFTER `country`,
  ADD COLUMN `adminUnit2` VARCHAR(100) NULL AFTER `adminUnit1`,
  ADD COLUMN `adminUnit3` VARCHAR(100) NULL AFTER `adminUnit2`,
  ADD COLUMN `locality` TEXT NULL AFTER `adminUnit3`,
  ADD COLUMN `localitySecurity` int(10) DEFAULT 0 COMMENT '0 = no security; 1 = hidden locality' AFTER `locality`,
  ADD COLUMN `localitySecurityReason` VARCHAR(100) NULL AFTER `localitySecurity`,
  ADD COLUMN `geodeticDatum` VARCHAR(45) NULL AFTER `localitySecurityReason`,
  ADD COLUMN `geoJson` TEXT NULL AFTER `geodeticDatum`,
  ADD COLUMN `verbatimCoordinates` VARCHAR(175) NULL AFTER `geoJson`,
  ADD COLUMN `georeferenceRemarks` VARCHAR(500) NULL AFTER `verbatimCoordinates`,
  ADD COLUMN `minimumElevationInMeters` INT(6) NULL AFTER `georeferenceRemarks`,
  ADD COLUMN `maximumElevationInMeters` INT(6) NULL AFTER `minimumElevationInMeters`,
  ADD COLUMN `verbatimElevation` VARCHAR(175) NULL AFTER `maximumElevationInMeters`,
  ADD COLUMN `verticalDatum` VARCHAR(45) NULL AFTER `verbatimElevation`,
  ADD COLUMN `minimumDepthInMeters` INT(6) NULL AFTER `verticalDatum`,
  ADD COLUMN `maximumDepthInMeters` INT(6) NULL AFTER `minimumDepthInMeters`,
  ADD COLUMN `verbatimDepth` VARCHAR(50) NULL AFTER `maximumDepthInMeters`,
  ADD COLUMN `distanceAboveSurfaceInMeters` VARCHAR(45) NULL AFTER `verbatimDepth`,
  ADD COLUMN `habitat` TEXT NULL AFTER `distanceAboveSurfaceInMeters`,
  ADD COLUMN `substrate` VARCHAR(500) NULL AFTER `habitat`,
  ADD COLUMN `locationRemarks` TEXT NULL AFTER `substrate`;
  

