CREATE TABLE `omoccurrences2` (
  `occid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `collid` int(10) unsigned NOT NULL,
  `dbpk` varchar(150) DEFAULT NULL,
  `basisOfRecord` varchar(32) DEFAULT 'PreservedSpecimen' COMMENT 'PreservedSpecimen, LivingSpecimen, HumanObservation',
  `occurrenceID` varchar(255) DEFAULT NULL COMMENT 'UniqueGlobalIdentifier',
  `catalogNumber` varchar(32) DEFAULT NULL,
  `otherCatalogNumbers` varchar(255) DEFAULT NULL,
  `institutionID` varchar(255) DEFAULT NULL,
  `institutionCode` varchar(64) DEFAULT NULL,
  `collectionID` varchar(255) DEFAULT NULL,
  `collectionCode` varchar(64) DEFAULT NULL,
  `organismID` varchar(150) DEFAULT NULL,
  `typeStatus` varchar(255) DEFAULT NULL,
  `recordedBy` varchar(255) DEFAULT NULL COMMENT 'Collector(s)',
  `recordNumber` varchar(45) DEFAULT NULL COMMENT 'Collector Number',
  `observerUid` int(10) unsigned DEFAULT NULL,
  `associatedCollectors` varchar(255) DEFAULT NULL COMMENT 'not DwC',
  `occurrenceRemarks` text DEFAULT NULL COMMENT 'General Notes',
  `informationWithheld` varchar(250) DEFAULT NULL,
  `dataGeneralizations` varchar(250) DEFAULT NULL,
  `associatedTaxa` text DEFAULT NULL COMMENT 'Associated Species',
  `dynamicProperties` text DEFAULT NULL,
  `verbatimAttributes` text DEFAULT NULL,
  `behavior` varchar(500) DEFAULT NULL,
  `reproductiveCondition` varchar(255) DEFAULT NULL COMMENT 'Phenology: flowers, fruit, sterile',
  `cultivationStatus` int(10) DEFAULT NULL COMMENT '0 = wild, 1 = cultivated',
  `establishmentMeans` varchar(150) DEFAULT NULL,
  `lifeStage` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `individualCount` varchar(45) DEFAULT NULL,
  `preparations` varchar(100) DEFAULT NULL,
  `availability` int(2) DEFAULT NULL,
  `disposition` varchar(250) DEFAULT NULL,
  `storageLocation` varchar(100) DEFAULT NULL,
  `duplicateQuantity` int(10) unsigned DEFAULT NULL,
  `labelProject` varchar(250) DEFAULT NULL,
  `language` varchar(20) DEFAULT NULL,
  `processingStatus` varchar(45) DEFAULT NULL,
  `recordID` varchar(45) DEFAULT NULL,
  `recordEnteredBy` varchar(250) DEFAULT NULL,
  `modified` datetime DEFAULT NULL COMMENT 'source dateLastModified',
  `dateLastModified` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `initialTimestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`occid`) USING BTREE,
  UNIQUE KEY `Index_collid` (`collid`,`dbpk`),
  UNIQUE KEY `UNIQUE_occurrenceID` (`occurrenceID`),
  KEY `IX_catalogNumber` (`catalogNumber`),
  KEY `IX_otherCatalogNumbers` (`otherCatalogNumbers`),
  KEY `IX_collector` (`recordedBy`),
  KEY `IX_observerUid_idx` (`observerUid`),
  KEY `IX_recordNumber` (`recordNumber`),
  KEY `IX_processingStatus` (`processingStatus`),
  KEY `occelevmax` (`maximumElevationInMeters`),
  KEY `occelevmin` (`minimumElevationInMeters`),
  KEY `Index_occurrences_cult` (`cultivationStatus`),
  KEY `Index_occurrences_typestatus` (`typeStatus`),
  KEY `Index_occurDateLastModifed` (`dateLastModified`),
  KEY `Index_occurDateEntered` (`dateEntered`),
  KEY `Index_occurRecordEnteredBy` (`recordEnteredBy`),
  KEY `IX_omoccurrences_recordID` (`recordID`),
  CONSTRAINT `FK_omoccurrences_collid` FOREIGN KEY (`collid`) REFERENCES `omcollections` (`CollID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_omoccurrences_uid` FOREIGN KEY (`observerUid`) REFERENCES `users` (`uid`)
) ENGINE=InnoDB;


CREATE TABLE `events` (
  `eventPK` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `clid` int(10) unsigned NOT NULL,
  `eventID` varchar(150) DEFAULT NULL,
  `parentEventID` varchar(150) DEFAULT NULL,
  `parentEventPK` int(10) unsigned NULL,
  `eventType` varchar(150) DEFAULT NULL,
  `isDefault` int(1) NOT NULL,
  `fieldNumber` varchar(45) DEFAULT NULL,
  `eventDate` date DEFAULT NULL,
  `eventDate2` date DEFAULT NULL,
  `eventTime` varchar(45) DEFAULT NULL,
  `eventTime2` varchar(45) DEFAULT NULL,
  `year` int(10) DEFAULT NULL,
  `month` int(10) DEFAULT NULL,
  `day` int(10) DEFAULT NULL,
  `startDayOfYear` int(10) DEFAULT NULL,
  `endDayOfYear` int(10) DEFAULT NULL,
  `verbatimEventDate` varchar(255) DEFAULT NULL,
  `habitat` text DEFAULT NULL COMMENT 'Habitat, substrait, etc',
  `substrate` varchar(500) DEFAULT NULL,
  `protocolID` varchar(150) DEFAULT NULL,
  `protocolName` varchar(150) DEFAULT NULL,
  `protocolDescription` text DEFAULT NULL,
  `protocolCitation` varchar(250) DEFAULT NULL,
  `sampleSizeValue` double DEFAULT NULL,
  `sampleSizeUnit` varchar(45) DEFAULT NULL,
  `samplingEffort` varchar(200) DEFAULT NULL,
  `fieldNotes` text DEFAULT NULL,
  `eventRemarks` varchar(100) DEFAULT NULL,
  `locationID` varchar(150) DEFAULT NULL,
  `higherGeography` varchar(250) DEFAULT NULL,
  `continent` varchar(45) DEFAULT NULL,
  `waterBody` varchar(75) DEFAULT NULL,
  `islandGroup` varchar(75) DEFAULT NULL,
  `island` varchar(75) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `countryCode` varchar(5) DEFAULT NULL,
  `adminUnit1` varchar(100) DEFAULT NULL,
  `adminUnit2` varchar(100) DEFAULT NULL,
  `adminUnit3` varchar(100) DEFAULT NULL,
  `locality` text DEFAULT NULL,
  `verbatimLocality` text DEFAULT NULL,
  `localitySecurity` int(10) DEFAULT 0 COMMENT '0 = no security; 1 = hidden locality',
  `localitySecurityReason` varchar(100) DEFAULT NULL,
  `decimalLatitude` double DEFAULT NULL,
  `decimalLongitude` double DEFAULT NULL,
  `geodeticDatum` varchar(255) DEFAULT NULL,
  `coordinateUncertaintyInMeters` int(10) unsigned DEFAULT NULL,
  `footprintWKT` text DEFAULT NULL,
  `geoJson` text DEFAULT NULL,
  `verbatimCoordinates` varchar(255) DEFAULT NULL,
  `georeferencedBy` varchar(255) DEFAULT NULL,
  `georeferencedDate` datetime DEFAULT NULL,
  `georeferenceRemarks` varchar(500) DEFAULT NULL,
  `minimumElevationInMeters` int(6) DEFAULT NULL,
  `maximumElevationInMeters` int(6) DEFAULT NULL,
  `verbatimElevation` varchar(255) DEFAULT NULL,
  `verticalDatum` varchar(45) DEFAULT NULL,
  `minimumDepthInMeters` int(11) DEFAULT NULL,
  `maximumDepthInMeters` int(11) DEFAULT NULL,
  `verbatimDepth` varchar(50) DEFAULT NULL,
  `minimumDistanceAboveSurfaceInMeters` int(11) DEFAULT NULL,
  `maximumDistanceAboveSurfaceInMeters` int(11) DEFAULT NULL,
  `locationRemarks` text DEFAULT NULL,
  `recordID` varchar(45) DEFAULT NULL,
  `createdUid` int(10) unsigned DEFAULT NULL,
  `modifiedTimestamp` timestamp NULL ON UPDATE current_timestamp(),
  `initialTimestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`eventPK`) USING BTREE,
  KEY `IX_clid` (`clid`),
  KEY `IX_eventID` (`eventID`),
  KEY `IX_parentEventID` (`eventID`),
  KEY `IX_eventType` (`eventType`),
  KEY `IX_eventDate` (`eventDate`),
  KEY `IX_eventDate2` (`eventDate2`),
  KEY `IX_locationID` (`locationID`),
  KEY `IX_country` (`country`),
  KEY `IX_adminUnit1` (`adminUnit1`),
  KEY `IX_adminUnit2` (`adminUnit2`),
  KEY `IX_adminUnit3` (`adminUnit3`),
  KEY `IX_decimalLatitute` (`decimalLatitude`),
  KEY `IX_decimalLongitute` (`decimalLongitude`),
  KEY `IX_localitySecurity` (`localitySecurity`),
  KEY `IX_elevMax` (`maximumElevationInMeters`),
  KEY `IX_elevMin` (`minimumElevationInMeters`),
  KEY `IX_recordID` (`recordID`),
  CONSTRAINT `FK_clid` FOREIGN KEY (`clid`) REFERENCES `fmchecklists` (`clid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_parentEventPK` FOREIGN KEY (`parentEventPK`) REFERENCES `events` (`eventPK`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_createdUid` FOREIGN KEY (`createdUid`) REFERENCES `users` (`uid`)
) ENGINE=InnoDB;

ALTER TABLE `fmchecklists` 
  DROP FOREIGN KEY `FK_checklists_uid`;

ALTER TABLE `fmchecklists` 
  DROP COLUMN `politicalDivision`,
  CHANGE COLUMN `access` `access` VARCHAR(45) NULL DEFAULT 'private' AFTER `type`,
  CHANGE COLUMN `cidKeyLimits` `cidKeyLimits` VARCHAR(250) NULL DEFAULT NULL AFTER `access`,
  CHANGE COLUMN `defaultSettings` `defaultSettings` VARCHAR(250) NULL DEFAULT NULL AFTER `cidKeyLimits`,
  CHANGE COLUMN `iconUrl` `iconUrl` VARCHAR(150) NULL DEFAULT NULL AFTER `defaultSettings`,
  CHANGE COLUMN `headerUrl` `headerUrl` VARCHAR(150) NULL DEFAULT NULL AFTER `iconUrl`,
  CHANGE COLUMN `percentEffort` `percentEffort` DOUBLE NULL DEFAULT NULL AFTER `dynamicSql`,
  CHANGE COLUMN `uid` `createdUid` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `modifiedTimestamp`,
  CHANGE COLUMN `locality` `locality` VARCHAR(1000) NULL DEFAULT NULL ,
  CHANGE COLUMN `guid` `sourceGUID` VARCHAR(45) NULL DEFAULT NULL ,
  CHANGE COLUMN `dateLastModified` `modifiedTimestamp` TIMESTAMP NULL DEFAULT NULL ;

ALTER TABLE `fmchecklists` 
  ADD CONSTRAINT `FK_checklists_uid`  FOREIGN KEY (`createdUid`)  REFERENCES `users` (`uid`);
  
  

