



CREATE TABLE `events` (
  `eventPK` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `clid` int(10) unsigned NOT NULL,
  `dbpk` varchar(150) DEFAULT NULL,
  `eventID` varchar(150) DEFAULT NULL,
  `parentEventID` varchar(150) DEFAULT NULL,
  `parentEventPK` int(10) unsigned NULL,
  `eventType` varchar(150) DEFAULT NULL,
  `fieldNumber` varchar(45) DEFAULT NULL,
  `eventDate` date DEFAULT NULL,
  `eventDate2` date DEFAULT NULL,
  `eventTime` varchar(45) DEFAULT NULL,
  `eventTime2` varchar(45) DEFAULT NULL,
  `year` int(10) DEFAULT NULL,
  `month` int(10) DEFAULT NULL,
  `day` int(10) DEFAULT NULL,
  `startDayOfYear` int(10) DEFAULT NULL,
  `endDayOfYear` int(10) DEFAULT NULL,
  `verbatimEventDate` varchar(255) DEFAULT NULL,
  `habitat` text DEFAULT NULL COMMENT 'Habitat, substrait, etc',
  `substrate` varchar(500) DEFAULT NULL,
  `samplingProtocol` varchar(250) DEFAULT NULL,
  `sampleSizeValue` double DEFAULT NULL,
  `sampleSizeUnit` varchar(45) DEFAULT NULL,
  `samplingEffort` varchar(200) DEFAULT NULL,
  `fieldNotes` text DEFAULT NULL,
  `eventRemarks` varchar(100) DEFAULT NULL,
  `locationID` varchar(150) DEFAULT NULL,
  `higherGeography` varchar(250) DEFAULT NULL,
  `continent` varchar(45) DEFAULT NULL,
  `waterBody` varchar(75) DEFAULT NULL,
  `islandGroup` varchar(75) DEFAULT NULL,
  `island` varchar(75) DEFAULT NULL,
  `countryCode` varchar(5) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `adminUnit1` varchar(100) DEFAULT NULL,
  `adminUnit2` varchar(100) DEFAULT NULL,
  `adminUnit3` varchar(100) DEFAULT NULL,
  `locality` text DEFAULT NULL,
  `verbatimLocality` text DEFAULT NULL,
  `localitySecurity` int(10) DEFAULT 0 COMMENT '0 = no security; 1 = hidden locality',
  `localitySecurityReason` varchar(100) DEFAULT NULL,
  `decimalLatitude` double DEFAULT NULL,
  `decimalLongitude` double DEFAULT NULL,
  `geodeticDatum` varchar(255) DEFAULT NULL,
  `coordinateUncertaintyInMeters` int(10) unsigned DEFAULT NULL,
  `footprintWKT` text DEFAULT NULL,
  `geoJson` text DEFAULT NULL,
  `verbatimCoordinates` varchar(255) DEFAULT NULL,
  `georeferencedBy` varchar(255) DEFAULT NULL,
  `georeferencedDate` datetime DEFAULT NULL,
  `georeferenceRemarks` varchar(500) DEFAULT NULL,
  `minimumElevationInMeters` int(6) DEFAULT NULL,
  `maximumElevationInMeters` int(6) DEFAULT NULL,
  `verbatimElevation` varchar(255) DEFAULT NULL,
  `verticalDatum` varchar(45) DEFAULT NULL,
  `minimumDepthInMeters` int(11) DEFAULT NULL,
  `maximumDepthInMeters` int(11) DEFAULT NULL,
  `verbatimDepth` varchar(50) DEFAULT NULL,
  `distanceAboveSurfaceInMeters` varchar(45) DEFAULT NULL,
  `locationRemarks` text DEFAULT NULL,
  `recordID` varchar(45) DEFAULT NULL,
  `createdUid` int(10) unsigned DEFAULT NULL,
  `modifiedTimestamp` timestamp NULL ON UPDATE current_timestamp(),
  `initialTimestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`eventPK`) USING BTREE,
  UNIQUE KEY `UNIQUE_occurrenceID` (`occurrenceID`),
  KEY `IX_country` (`country`),
  KEY `IX_adminUnit1` (`adminUnit1`),
  KEY `IX_adminUnit2` (`adminUnit2`),
  KEY `IX_adminUnit3` (`adminUnit3`),
  KEY `Index_municipality` (`municipality`),
  KEY `Index_collnum` (`recordNumber`),
  KEY `Index_catalognumber` (`catalogNumber`),
  KEY `Index_eventDate` (`eventDate`),
  KEY `Index_occurrences_procstatus` (`processingStatus`),
  KEY `occelevmax` (`maximumElevationInMeters`),
  KEY `occelevmin` (`minimumElevationInMeters`),
  KEY `Index_occurrences_cult` (`cultivationStatus`),
  KEY `Index_occurrences_typestatus` (`typeStatus`),
  KEY `Index_occurDateLastModifed` (`dateLastModified`),
  KEY `Index_occurDateEntered` (`dateEntered`),
  KEY `Index_occurRecordEnteredBy` (`recordEnteredBy`),
  KEY `Index_locality` (`locality`(100)),
  KEY `Index_otherCatalogNumbers` (`otherCatalogNumbers`),
  KEY `IX_omoccur_eventDate2` (`eventDate2`),
  KEY `Index_locationID` (`locationID`),
  KEY `Index_eventID` (`eventID`),
  KEY `Index_occur_localitySecurity` (`localitySecurity`),
  KEY `IX_occurrences_lat` (`decimalLatitude`),
  KEY `IX_occurrences_lng` (`decimalLongitude`),
  KEY `IX_omoccurrences_recordID` (`recordID`),
  CONSTRAINT `FK_omoccurrences_collid` FOREIGN KEY (`collid`) REFERENCES `omcollections` (`CollID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_omoccurrences_tid` FOREIGN KEY (`tidInterpreted`) REFERENCES `taxa` (`tid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_omoccurrences_uid` FOREIGN KEY (`observerUid`) REFERENCES `users` (`uid`)
) ENGINE=InnoDB;

ALTER TABLE `fmchecklists` 
  DROP FOREIGN KEY `FK_checklists_uid`;

ALTER TABLE `fmchecklists` 
  DROP COLUMN `politicalDivision`,
  CHANGE COLUMN `access` `access` VARCHAR(45) NULL DEFAULT 'private' AFTER `type`,
  CHANGE COLUMN `cidKeyLimits` `cidKeyLimits` VARCHAR(250) NULL DEFAULT NULL AFTER `access`,
  CHANGE COLUMN `defaultSettings` `defaultSettings` VARCHAR(250) NULL DEFAULT NULL AFTER `cidKeyLimits`,
  CHANGE COLUMN `iconUrl` `iconUrl` VARCHAR(150) NULL DEFAULT NULL AFTER `defaultSettings`,
  CHANGE COLUMN `headerUrl` `headerUrl` VARCHAR(150) NULL DEFAULT NULL AFTER `iconUrl`,
  CHANGE COLUMN `uid` `createdUid` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `modifiedTimestamp`,
  CHANGE COLUMN `locality` `locality` VARCHAR(1000) NULL DEFAULT NULL ,
  CHANGE COLUMN `percentEffort` `percentEffort` DOUBLE NULL DEFAULT NULL ,
  CHANGE COLUMN `guid` `sourceGUID` VARCHAR(45) NULL DEFAULT NULL ,
  CHANGE COLUMN `dateLastModified` `modifiedTimestamp` TIMESTAMP NULL DEFAULT NULL ;

ALTER TABLE `fmchecklists` 
  ADD CONSTRAINT `FK_checklists_uid`  FOREIGN KEY (`createdUid`)  REFERENCES `users` (`uid`);
  
ALTER TABLE `fmchecklists` 
  ADD COLUMN `newcol` VARCHAR(45) NULL AFTER `initialTimestamp`,
  
  `samplingProtocol` varchar(250) DEFAULT NULL,
  `locationID` varchar(150) DEFAULT NULL,
  `higherGeography` varchar(250) DEFAULT NULL,
  `continent` varchar(45) DEFAULT NULL,
  `waterBody` varchar(75) DEFAULT NULL,
  `islandGroup` varchar(75) DEFAULT NULL,
  `island` varchar(75) DEFAULT NULL,
  `countryCode` varchar(5) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `adminUnit1` varchar(100) DEFAULT NULL,
  `adminUnit2` varchar(100) DEFAULT NULL,
  `adminUnit3` varchar(100) DEFAULT NULL,
  `locality` text DEFAULT NULL,
  `localitySecurity` int(10) DEFAULT 0 COMMENT '0 = no security; 1 = hidden locality',
  `localitySecurityReason` varchar(100) DEFAULT NULL,
  `geodeticDatum` varchar(255) DEFAULT NULL,

  `geoJson` text DEFAULT NULL,
  `verbatimCoordinates` varchar(255) DEFAULT NULL,
  `georeferenceRemarks` varchar(500) DEFAULT NULL,
  `minimumElevationInMeters` int(6) DEFAULT NULL,
  `maximumElevationInMeters` int(6) DEFAULT NULL,
  `verbatimElevation` varchar(255) DEFAULT NULL,
  `verticalDatum` varchar(45) DEFAULT NULL,
  `minimumDepthInMeters` int(11) DEFAULT NULL,
  `maximumDepthInMeters` int(11) DEFAULT NULL,
  `verbatimDepth` varchar(50) DEFAULT NULL,
  `distanceAboveSurfaceInMeters` varchar(45) DEFAULT NULL,
  `habitat` text DEFAULT NULL COMMENT 'Habitat, substrait, etc',
  `substrate` varchar(500) DEFAULT NULL,
  `locationRemarks` text DEFAULT NULL,


